name: Node Build.
on:  [push]
jobs:
mainbuild:
runs-on: ${{ matrix.os }}
strategy:
matrix: 
  node-version: [12.x]
  os: [windows-latest]
  steps:
  - uses: actions/checkout@v2
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}

      name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
